// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaotMwOLvlU7Oi3UMuqJR5NdlM6mofwDc',
    appId: '1:147272443808:web:260cd79bffc2720245e6c5',
    messagingSenderId: '147272443808',
    projectId: 'gdgproject-d6ad2',
    authDomain: 'gdgproject-d6ad2.firebaseapp.com',
    storageBucket: 'gdgproject-d6ad2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCB9HHQ0fS4fTFm2nHTS7JyRQaorM-gOE',
    appId: '1:147272443808:android:45b99891d1a53fc645e6c5',
    messagingSenderId: '147272443808',
    projectId: 'gdgproject-d6ad2',
    storageBucket: 'gdgproject-d6ad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMXmHK3Zbm4StcFYcx0E1HPKwzWZ0y96E',
    appId: '1:147272443808:ios:d320b2fa02bf2de445e6c5',
    messagingSenderId: '147272443808',
    projectId: 'gdgproject-d6ad2',
    storageBucket: 'gdgproject-d6ad2.firebasestorage.app',
    iosBundleId: 'com.example.gdgProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMXmHK3Zbm4StcFYcx0E1HPKwzWZ0y96E',
    appId: '1:147272443808:ios:d320b2fa02bf2de445e6c5',
    messagingSenderId: '147272443808',
    projectId: 'gdgproject-d6ad2',
    storageBucket: 'gdgproject-d6ad2.firebasestorage.app',
    iosBundleId: 'com.example.gdgProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaotMwOLvlU7Oi3UMuqJR5NdlM6mofwDc',
    appId: '1:147272443808:web:c22421839a7715de45e6c5',
    messagingSenderId: '147272443808',
    projectId: 'gdgproject-d6ad2',
    authDomain: 'gdgproject-d6ad2.firebaseapp.com',
    storageBucket: 'gdgproject-d6ad2.firebasestorage.app',
  );
}
